// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD724HcpXJuG5ON0RY7VQPurObCgWF7fSs',
    appId: '1:457757812633:web:49ba7ae0a6754cb0fb9508',
    messagingSenderId: '457757812633',
    projectId: 'flutter-chat-app-160b0',
    authDomain: 'flutter-chat-app-160b0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-160b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVQw_3GFuonAyDL4Oo_Dm2oMbYur5wduU',
    appId: '1:457757812633:android:0269a6a147f09d5efb9508',
    messagingSenderId: '457757812633',
    projectId: 'flutter-chat-app-160b0',
    storageBucket: 'flutter-chat-app-160b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4CrDjf651ziR6G2phxp9rxRnyTZ90Ow8',
    appId: '1:457757812633:ios:e1168489eb9f43d2fb9508',
    messagingSenderId: '457757812633',
    projectId: 'flutter-chat-app-160b0',
    storageBucket: 'flutter-chat-app-160b0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}